name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Run ESLint check
        run: yarn lint
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Build apps
        run: yarn build

      - name: Login to Docker Registry
        run: echo ${{ secrets.DOCKER_REGISTRY_PASSWORD }} | docker login -u ${{ secrets.DOCKER_REGISTRY_USERNAME }} --password-stdin ${{ secrets.DOCKER_REGISTRY_URL }}

      - name: Build and Push Docker Image
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap
          docker buildx build --platform linux/amd64 --push -t ${{ env.DOCKER_REPOSITORY_BASE_URL }}/kir-mail-gateway:latest -f apps/gateway/Dockerfile .
          docker buildx build --platform linux/amd64 --push -t ${{ env.DOCKER_REPOSITORY_BASE_URL }}/kir-mail-microsoft-consumer:latest -f apps/microsoft-consumer/Dockerfile .
          docker buildx build --platform linux/amd64 --push -t ${{ env.DOCKER_REPOSITORY_BASE_URL }}/kir-mail-mailgun-consumer:latest -f apps/mailgun-consumer/Dockerfile .

      - name: Logout from Docker Registry
        run: docker logout ${{ secrets.DOCKER_REGISTRY_URL }}

